Repository deliciousmods/1956_beta, pull requests merged in 2025-05, with the labels that each got.

#3159 Spring 25 advisor pack (Part 1)
  common/characters/ENG.txt
  common/characters/POR.txt
  common/characters/RAJ.txt
  common/characters/SWE.txt
  common/characters/TUR.txt
  common/country_leader/r56_traits.txt
  common/decisions/r56_prospecting.txt
  common/national_focus/r56_portugal.txt
  history/countries/ENG - Britain.txt
  history/countries/POR - Portugal.txt
  history/countries/RAJ - British Raj.txt
  history/countries/SWE - Sweden.txt
  history/countries/TUR - Turkey.txt
  localisation/english/r56_traits_l_english.yml
Labels: minor, On-Going

#3133 UK communist path changes / tweaks
  common/national_focus/uk.txt
Labels: bug, minor, Country Suggestions

#3153 HOL-INS April Rework
  common/characters/HOL.txt
  common/characters/INS.txt
  common/decisions/INS.txt
  common/decisions/categories/INS_decision_categories.txt
  common/ideas/indonesia.txt
  common/military_industrial_organization/organizations/00_generic_organization.txt
  common/military_industrial_organization/organizations/INS_organization.txt
  common/national_focus/indonesia.txt
  common/national_focus/netherlands.txt
  common/national_focus/netherlands_MtG.txt
  common/scripted_localisation/r56_INS_scripted_localisation.txt
  common/units/names_ships/INS_ship_names.txt
  events/indonesia.txt
  events/netherlands.txt
  gfx/flags/INS_fascism.tga
  gfx/flags/medium/INS_fascism.tga
  gfx/flags/small/INS_fascism.tga
  gfx/interface/ideas/hol/advisors/r56_idea_HOL_advisor_agathon_sickinghe.dds
  gfx/interface/ideas/hol/advisors/r56_idea_HOL_advisor_francois_tsant.dds
  gfx/interface/ideas/hol/advisors/r56_idea_HOL_advisor_george_van_goudriaan.dds
  gfx/interface/ideas/hol/advisors/r56_idea_HOL_advisor_juliana.dds
  gfx/interface/ideas/ins/advisors/r56_idea_INS_advisor_margono_joyohadikusumo.dds
  gfx/leaders/HOL/r56_portrait_HOL_Juliana.dds
  history/countries/HOL - Holland.txt
  history/countries/INS - Indonesia.txt
  interface/_r56_leader_portraits.gfx
  interface/r56_ideas_advisors.gfx
  localisation/english/HOL_l_english.yml
  localisation/english/INS_l_english.yml
  localisation/english/r56_countries_cosmetic_l_english.yml
Labels: bug, moderate, tweak

#3164 Portugal May 2025
  common/ideas/r56_portugal.txt
  common/national_focus/r56_portugal.txt
  events/r56_portugal.txt
  localisation/english/POR_l_english.yml
Labels: minor

#3166 Small adjustements
  common/characters/SAF.txt
  common/country_leader/00_traits.txt
  common/ideas/south_africa.txt
  common/intelligence_agencies/00_intelligence_agencies.txt
  common/military_industrial_organization/organizations/ENG_organization.txt
  common/military_industrial_organization/organizations/SAF_organization_r56.txt
  common/national_focus/france.txt
  common/national_focus/south_africa.txt
  common/scripted_localisation/r56_scripted_localisation.txt
  gfx/event_pictures/BEL/news_event_BEL_rexist_military_parade.dds
  gfx/event_pictures/SAF/news_event_SAF_join_faction_germany.dds
  gfx/event_pictures/USA/news_event_USA_join_faction_PRC.dds
  gfx/interface/goals/fra/r56_goal_FRA_french_algeria.dds
  history/countries/SAF - South Africa.txt
  interface/r56_eventpictures.gfx
  interface/r56_goals.gfx
  interface/r56_goals_shine.gfx
  localisation/english/SAF_l_english.yml
Labels: bug, minor, tweak

#3168 Remove Emo Map 💀
  map/terrain.bmp
  map/world_normal.bmp
Labels: bug, minor

#3170 Finland Enhancements
  common/ai_focuses/FIN.txt
  common/ai_strategy/r56_FIN.txt
  common/ai_strategy/r56_GER.txt
  common/ai_strategy/r56_SOV.txt
  common/ai_strategy_plans/FIN_R56_alternate_strategy_plan.txt
  common/ai_strategy_plans/FIN_R56_historical_strategy_plan.txt
  common/ai_strategy_plans/FIN_alternate_strategy_plan.txt
  common/characters/FIN.txt
  common/country_leader/r56_traits.txt
  common/game_rules/00_game_rules.txt
  common/ideas/r56_finland.txt
  common/national_focus/finland.txt
  common/national_focus/r56_finland.txt
  common/on_actions/r56_focus_tree_selection_on_actions.txt
  common/scripted_effects/FIN_scripted_effects.txt
  common/technologies/land_doctrine.txt
  events/Finland.txt
  gfx/interface/ideas/fin/advisors/r56_idea_FIN_aimo_aaltonen.dds
  gfx/interface/ideas/fin/advisors/r56_idea_FIN_otto_wille_kuusinen.dds
  gfx/interface/ideas/fin/advisors/r56_idea_FIN_vilho_annala.dds
  history/countries/FIN - Finland.txt
  interface/_r56_leader_portraits.gfx
  interface/r56_ideas_advisors.gfx
  localisation/english/FIN_l_english.yml
  localisation/english/r56_traits_l_english.yml
Labels: enhancement, major, tweak, On-Going, Country Suggestions
